[package]
name = "mcfly"
version = "0.2.0"
authors = ["Andrew Cantino <cantino@users.noreply.github.com>"]

[profile.release]
lto = true

[dependencies]
clap = "2.32.0"
csv = "1"
dirs = "1.0"
libc = "0.2"
rand = "0.5.5"
regex = "1"
relative-path = "0.4.0"
shellexpand = "1.0.0"
termion = "1.5.1"
unicode-segmentation = "1.2.1"

[dependencies.rusqlite]
version = "0.15.0"
features = ["bundled", "functions"]
