[package]
name = "bash_wizard"
version = "0.1.0"
authors = ["Andrew Cantino <cantino@users.noreply.github.com>"]

[dependencies]
clap = "2.32.0"
termion = "1.5.1"
unicode-segmentation = "1.2.1"
libc = "0.2"
regex = "1"

[dependencies.rusqlite]
version = "0.14.0"
features = ["bundled"]
